server:
  domain: 'localhost'
  host: '0.0.0.0'
  port: 80
  jwt:
    signingKey: 'img-hosting'
    expiredTime: 7200000
  image:
    limit: 12
    supportExts: ['image/jpeg', 'image/gif', 'image/png', 'image/tiff', 'image/x-icon']
  middlewares:
    cors:
      active: true
      allowOrigins: ['*']
      allowMethods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE']
    gzip:
      active: true
      level: 5
    log:
      active: true
      format: '${time_rfc3339_nano} ${remote_ip} ${host} ${method} ${uri} ${status} ${latency_human} ${bytes_in} ${bytes_out}'
      output: 'stdout'
    limit:
      active: true
      size: '4MB'

database:
  mysql:
    user: 'root'
    password: ''
    address: 'localhost:3306'
    dbname: 'img_hosting'